spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mini_blog
    username: root
    password: 1234

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
debug: false
logging:
  level:
    root: info
    org.springframework: warn
    com.baomidou.mybatisplus: warn