server:
  address: 0.0.0.0

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mini_blog
    username: root
    password: Chenqiao@2

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
